<<<<<<< HEAD
# Generated by Django 3.0.4 on 2020-03-14 18:44
=======
# Generated by Django 3.0.4 on 2020-06-15 18:37
>>>>>>> step_0_start

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('picture', models.URLField(default='https://via.placeholder.com/300x400?text=No+photo', max_length=900)),
=======
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.URLField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSSSDAflI2W07ixtGLC1dxDGHkR5x9rek2BHlY3q07ZoxaTwv_d&usqp=CAU', max_length=900)),
                ('name', models.CharField(max_length=200)),
>>>>>>> step_0_start
                ('rating', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)])),
                ('notes', models.TextField(default='', max_length=2000)),
            ],
        ),
    ]
